import { AddStudentType } from '../model/types/addStudent';

export const addStudentInitial: AddStudentType = {
    login: null,
    password: null,
    email: null,
    first_name: null,
    last_name: null,
    patronymic: null,
    govid: null,
    govid_issue_date: null,
    birth_date: null,
    reason_for_missing_govid_id: null,
    gender_id: null,
    citizenship_id: null,
    nationality_id: null,
    residential_address: null,
    temporary_residence_address: null,
    enrollment_type_id: null,
    arrival_date: null,
    is_arrival_from_id: null,
    phone_number: null,
    is_finished_edu_type_id: null,
    residence_type_id: null,
    study_duration_id: null,
    study_course_id: null,
    edu_lang_id: null,
    edu_form_id: null,
    edu_speciality_id: null,
    edu_classifier_id: null,
    is_study_in_dual_system: false,
    is_study_in_productive_employment: false,
    is_completed_training_at_competence_center: false,
    is_study_in_worldskills: false,
    is_need_hostel_type_id: null,
    is_live_at_hostel: false,
    financing_source_type_id: null,
    quota_id: null,
    is_involved_in_social_activities: false,
    is_orphan: false,
    is_without_parental_care: false,
    is_disabled_person: false,
    material_assistance_type_id: null,
    is_from_young_family: false,
};
