import {
    AnyAction, CombinedState, EnhancedStore, Reducer, ReducersMapObject,
} from '@reduxjs/toolkit';
import { AxiosInstance } from 'axios';
import { To } from '@remix-run/router';
import { NavigateOptions } from 'react-router/dist/lib/context';
import { TableFiltersSchema, TableFiltersSelectedSchema } from 'features/TableFilters';
import { AddStudentSchema } from 'features/Students/AddStudent';
import { EditStudentSchema } from 'features/Students/EditStudent';
import { StudentDetailSchema } from 'entities/StudentDetail';
import { LoginSchema } from 'features/Login';
import { UserSchema } from 'entities/User';
import { TableSortSchema } from 'features/TableSort';
import { StudentsSchema } from 'entities/Students';
import { ImportStudentsSchema } from 'features/Students/ImportStudents';
import { EnrollmentTypesSchema } from 'entities/EnrollmentTypes';
import { AddEnrollmentTypeSchema } from 'features/EnrollmentTypes/AddEnrollmentType';
import { EnrollmentTypeDetailSchema } from 'entities/EnrollmentTypeDetail';
import { EditEnrollmentTypeSchema } from 'features/EnrollmentTypes/EditEnrollmentType';
import { CitizenshipSchema } from 'entities/Citizenship';
import { CitizenshipDetailSchema } from 'entities/CitizenshipDetail';
import { AddCitizenshipSchema } from 'features/Citizenship/AddCitizenship';
import { EditCitizenshipSchema } from 'features/Citizenship/EditCitizenship';
import { NationalitiesSchema } from 'entities/Nationalities';
import { NationalityDetailSchema } from 'entities/NationalityDetail';
import { EditNationalitySchema } from 'features/Nationalities/EditNationality';
import { AddNationalitySchema } from 'features/Nationalities/AddNationality';
import { EduLanguagesSchema } from 'entities/EduLanguages';
import { EduLanguageDetailSchema } from 'entities/EduLanguageDetail';
import { EditEduLanguageSchema } from 'features/EduLanguages/EditEduLanguage';
import { AddEduLanguageSchema } from 'features/EduLanguages/AddEduLanguage';
import { FinishedEduTypesSchema } from 'entities/FinishedEduTypes';
import { FinishedEduTypeDetailSchema } from 'entities/FinishedEduTypeDetail/model/types/finishedEduTypeDetail';
import { AddFinishedEduTypeSchema } from 'features/FinishedEduTypes/AddFinishedEduType';
import { EditFinishedEduTypeSchema } from 'features/FinishedEduTypes/EditFinishedEduType';
import { EduCoursesSchema } from 'entities/EduCourses';
import { EduCourseDetailSchema } from 'entities/EduCourseDetail/model/types/eduCourseDetail';
import { AddEduCourseSchema } from 'features/EduCourses/AddEduCourse';
import { EditEduCourseSchema } from 'features/EduCourses/EditEduCourse';
import { StudyDirectionsSchema } from 'entities/StudyDirections';
import { StudyDirectionDetailSchema } from 'entities/StudyDirectionDetail';
import { AddStudyDirectionSchema } from 'features/StudyDirections/AddStudyDirection';
import { EditStudyDirectionSchema } from 'features/StudyDirections/EditStudyDirection';
import { StudyDurationsSchema } from 'entities/StudyDurations';
import { StudyDurationDetailSchema } from 'entities/StudyDurationDetail/model/types/studyDurationDetail';
import { AddStudyDurationSchema } from 'features/StudyDurations/AddStudyDuration';
import { EditStudyDurationSchema } from 'features/StudyDurations/EditStudyDuration';
import { QualificationsSchema } from 'entities/Qualifications';
import { QualificationDetailSchema } from 'entities/QualificationDetail';
import { AddQualificationSchema } from 'features/Qualifications/AddQualification';
import { EditQualificationSchema } from 'features/Qualifications/EditQualification';
import { EduFormsSchema } from 'entities/EduForms';
import { EduFormDetailSchema } from 'entities/EduFormDetail';
import { AddEduFormSchema } from 'features/EduForms/AddEduForm';
import { EditEduFormSchema } from 'features/EduForms/EditEduForm';
import { ResidenceTypesSchema } from 'entities/ResidenceTypes';
import { ResidenceTypeDetailSchema } from 'entities/ResidenceTypeDetail';
import { AddResidenceTypeSchema } from 'features/ResidenceTypes/AddResidenceType';
import { EditResidenceTypeSchema } from 'features/ResidenceTypes/EditResidenceType';
import { SpecialtiesSchema } from 'entities/Specialties';
import { SpecialityDetailSchema } from 'entities/SpecialityDetail';
import { AddSpecialitySchema } from 'features/Specialties/AddSpeciality';
import { EditSpecialitySchema } from 'features/Specialties/EditSpeciality';
import { FinSourcesSchema } from 'entities/FinSources';
import { FinSourceDetailSchema } from 'entities/FinSourceDetail';
import { AddFinSourceSchema } from 'features/FinSources/AddFinSource';
import { EditFinSourceSchema } from 'features/FinSources/EditFinSource';
import { ArrivalSourcesSchema } from 'entities/ArrivalSources';
import { ArrivalSourceDetailSchema } from 'entities/ArrivalSourceDetail';
import { AddArrivalSourceSchema } from 'features/ArrivalSources/AddArrivalSource';
import { EditArrivalSourceSchema } from 'features/ArrivalSources/EditArrivalSource';
import { PracticeTypesSchema } from 'entities/PracticeTypes';
import { PracticeTypeDetailSchema } from 'entities/PracticeTypeDetail';
import { AddPracticeTypeSchema } from 'features/PracticeTypes/AddPracticeType';
import { EditPracticeTypeSchema } from 'features/PracticeTypes/EditPracticeType';
import { EventsTypesSchema } from 'entities/EventsTypes';
import { EventsTypeDetailSchema } from 'entities/EventsTypeDetail';
import { AddEventsTypeSchema } from 'features/EventsTypes/AddEventsType';
import { EditEventsTypeSchema } from 'features/EventsTypes/EditEventsType';
import { StudentSectionsSchema } from 'entities/StudentSections';
import { StudentSectionDetailSchema } from 'entities/StudentSectionDetail';
import { AddStudentSectionSchema } from 'features/StudentSections/AddStudentSection';
import { EditStudentSectionSchema } from 'features/StudentSections/EditStudentSection';
import { PerformanceTypesSchema } from 'entities/PerformanceTypes';
import { PerformanceTypeDetailSchema } from 'entities/PerformanceTypeDetail';
import { AddPerformanceTypeSchema } from 'features/PerformanceTypes/AddPerformanceType';
import { EditPerformanceTypeSchema } from 'features/PerformanceTypes/EditPerformanceType';
import { StudentClubsSchema } from 'entities/StudentClubs';
import { StudentClubDetailSchema } from 'entities/StudentClubDetail';
import { AddStudentClubSchema } from 'features/StudentClubs/AddStudentClub';
import { EditStudentClubSchema } from 'features/StudentClubs/EditStudentClub';
import { ExportStudentsSchema } from 'features/Students/ExportStudents';
import { SettingsMainCollegeSchema } from 'entities/Settings/SettingsMainCollege';
import { EducationalModulesSchema } from 'entities/EducationalModules';
import { AddEduModuleSchema } from 'features/EduModules/AddEduModule';
import { EducationalModuleDetailSchema } from 'entities/EducationalModuleDetail';
import { EditEduModuleSchema } from 'features/EduModules/EditEduModule';
import { AddEduUnitSchema } from 'features/EduUnits/AddEduUnit';
import { EditEduUnitSchema } from 'features/EduUnits/EditEduUnit';
import { EducationalUnitDetailSchema } from 'entities/EducationalUnitDetail';
import { CurriculumSubjectsSchema } from 'entities/CurriculumSubjects';
import { CurriculumSubjectsDetailSchema } from 'entities/CurriculumSubjectsDetail';
import { AddCurriculumSubjectSchema } from 'features/CurriculumSubjects/AddCurriculumSubject';
import { EditCurriculumSubjectSchema } from 'features/CurriculumSubjects/EditCurriculumSubject';
import { StandardCurriculumSchema } from 'entities/StandardCurriculum';
import { AddStandardCurriculumSchema } from 'features/StandardCurriculum/AddStandardCurriculum';
import { EditStandardCurriculumSchema } from 'features/StandardCurriculum/EditStandardCurriculum';
import { StandardCurriculumDetailSchema } from 'entities/StandardCurriculumDetail';
import { WorkingCurriculumSchema } from 'entities/WorkingCurriculum';
import { AddWorkingCurriculumSchema } from 'features/WorkingCurriculum/AddWorkingCurriculum';
import { EducationBasesSchema } from 'entities/EducationBases';
import { WorkingCurriculumDetailSchema } from 'entities/WorkingCurriculumDetail';
import { EditWorkingCurriculumSchema } from 'features/WorkingCurriculum/EditWorkingCurriculum';
import { WorkingCurriculumTrainingScheduleSchema } from 'entities/WorkingCurriculumTrainingSchedule';
import { StudentGroupsSchema } from 'entities/StudentGroups';
import { AddStudentGroupSchema } from 'features/StudentGroups/AddStudentGroups';
import { LanguagesSchema } from 'entities/Languages';
import { EditStudentGroupsSchema } from 'features/StudentGroups/EditStudentGroups';
import { StudentGroupDetailSchema } from 'entities/StudentGroupDetail';
import { TrainingScheduleSchema } from 'entities/TrainingSchedule';
import { TrainingScheduleDetailSchema } from 'entities/TrainingScheduleDetail';
import { WorkingCurriculumExtractSchema } from 'entities/WorkingCurriculumExtract';
import { EduActivitiesTypesSchema } from 'entities/EduActivitiesTypes';
import { StudentsInGroupsSchema } from 'entities/StudentsInGroups';
import { StudentsTableFieldsSchema } from 'features/Students/StudentsTableFields';
import { EmployeesSchema } from 'entities/Employees';
import { EmployeeDetailSchema } from 'entities/EmployeeDetail';
import { AddEmployeeSchema } from 'features/Employees/AddEmployee';
import { EditEmployeeSchema } from 'features/Employees/EditEmployee';
import { EmployeesTableFieldsSchema } from 'features/Employees/EmployeesTableFields';
import { EmployeeCategoriesSchema } from 'entities/EmployeeCategories';
import { EmployeeCategoryDetailSchema } from 'entities/EmployeeCategoryDetail';
import { AddEmployeeCategorySchema } from 'features/EmployeeCategories/AddEmployeeCategory';
import { EditEmployeeCategorySchema } from 'features/EmployeeCategories/EditEmployeeCategory';
import { EmployeePositionsSchema } from 'entities/EmployeePositions';
import { EmployeePositionDetailSchema } from 'entities/EmployeePositionDetail';
import { AddEmployeePositionSchema } from 'features/EmployeePositions/AddEmployeePosition';
import { EditEmployeePositionSchema } from 'features/EmployeePositions/EditEmployeePosition';
import { EmployeeEducationsSchema } from 'entities/EmployeeEducations';
import { EmployeeEducationDetailSchema } from 'entities/EmployeeEducationDetail';
import { AddEmployeeEducationSchema } from 'features/EmployeeEducations/AddEmployeeEducation';
import { EditEmployeeEducationSchema } from 'features/EmployeeEducations/EditEmployeeEducation';
import { AddEmployeeSubjectSchema } from 'features/Employees/AddEmployeeSubject';
import { AddEmployeePositionToEmployeeSchema } from 'features/Employees/AddEmployeePosition';
import { TrainingScheduleHeaderSchema } from 'entities/TrainingScheduleSchema';
import { SubjectsScheduleSchema } from 'entities/SubjectsSchedule';
import { SubjectsScheduleDetailSchema } from 'entities/SubjectsScheduleDetail';
import { SubjectsScheduleDetailActionsSchema } from 'features/SubjectsScheduleDetail';
import { ClassRoomsSchema } from 'entities/ClassRooms';
import { SubjectsScheduleWorkloadSchema } from 'entities/SubjectsScheduleWorkload';
import { AddStudentGroupsAssistantSchema } from 'features/StudentGroups/Assistant/AddStudentGroups';
import { AutoDistributionStudentGroupsSchema } from 'features/StudentGroups/Assistant/AutoDistributionStudentsGroups';

export interface StateSchema {
    user: UserSchema;
    students: StudentsSchema;
    tableSort: TableSortSchema;
    tableFiltersSelected: TableFiltersSelectedSchema;

    // async-reducers
    tableFilters?: TableFiltersSchema;
    studentsTableFields?: StudentsTableFieldsSchema;
    addNewStudent?: AddStudentSchema;
    editStudent?: EditStudentSchema;
    exportStudents?: ExportStudentsSchema;
    studentDetail?: StudentDetailSchema;
    login?: LoginSchema;
    importStudents?: ImportStudentsSchema;
    enrollmentTypes?: EnrollmentTypesSchema;
    addEnrollmentType?: AddEnrollmentTypeSchema;
    enrollmentTypeDetail?: EnrollmentTypeDetailSchema;
    editEnrollmentType?: EditEnrollmentTypeSchema;
    citizenship?: CitizenshipSchema;
    citizenshipDetail?: CitizenshipDetailSchema;
    addCitizenship?: AddCitizenshipSchema;
    editCitizenship?: EditCitizenshipSchema;
    nationalities?: NationalitiesSchema;
    nationalityDetail?: NationalityDetailSchema;
    addNationality?: AddNationalitySchema;
    editNationality?: EditNationalitySchema;
    eduLanguages?: EduLanguagesSchema;
    eduLanguagesDetail?: EduLanguageDetailSchema;
    editEduLanguage?: EditEduLanguageSchema;
    addEduLanguage?: AddEduLanguageSchema;
    finishedEduTypes?: FinishedEduTypesSchema;
    finishedEduTypesDetail?: FinishedEduTypeDetailSchema;
    addFinishedEduType?: AddFinishedEduTypeSchema;
    editFinishedEduType?: EditFinishedEduTypeSchema;
    eduCourses?: EduCoursesSchema;
    eduCourseDetail?: EduCourseDetailSchema;
    addEduCourse?: AddEduCourseSchema;
    editEduCourse?: EditEduCourseSchema;
    studyDirections?: StudyDirectionsSchema;
    studyDirectionDetail?: StudyDirectionDetailSchema;
    addStudyDirection?: AddStudyDirectionSchema;
    editStudyDirection?: EditStudyDirectionSchema;
    studyDurations?: StudyDurationsSchema;
    studyDurationDetail?: StudyDurationDetailSchema;
    addStudyDuration?: AddStudyDurationSchema;
    editStudyDuration?: EditStudyDurationSchema;
    qualifications?: QualificationsSchema;
    qualificationDetail?: QualificationDetailSchema;
    addQualification?: AddQualificationSchema;
    editQualification?: EditQualificationSchema;
    eduForms?: EduFormsSchema;
    eduFormDetail?: EduFormDetailSchema;
    addEduForm?: AddEduFormSchema;
    editEduForm?: EditEduFormSchema;
    residenceTypes?: ResidenceTypesSchema;
    residenceTypeDetail?: ResidenceTypeDetailSchema;
    addResidenceType?: AddResidenceTypeSchema;
    editResidenceType?: EditResidenceTypeSchema;
    specialties?: SpecialtiesSchema;
    specialityDetail?: SpecialityDetailSchema;
    addSpeciality?: AddSpecialitySchema;
    editSpeciality?: EditSpecialitySchema;
    finSources?: FinSourcesSchema;
    finSourcesDetail?: FinSourceDetailSchema;
    addFinSource?: AddFinSourceSchema;
    editFinSource?: EditFinSourceSchema;
    arrivalSources?: ArrivalSourcesSchema;
    arrivalSourceDetail?: ArrivalSourceDetailSchema;
    addArrivalSource?: AddArrivalSourceSchema;
    editArrivalSource?: EditArrivalSourceSchema;
    practiceTypes?: PracticeTypesSchema;
    practiceTypeDetail?: PracticeTypeDetailSchema;
    addPracticeType?: AddPracticeTypeSchema;
    editPracticeType?: EditPracticeTypeSchema;
    eventsTypes?: EventsTypesSchema;
    eventsTypeDetail?: EventsTypeDetailSchema;
    addEventsType?: AddEventsTypeSchema;
    editEventsType?: EditEventsTypeSchema;
    studentSections?: StudentSectionsSchema;
    studentSectionDetail?: StudentSectionDetailSchema;
    addStudentSection?: AddStudentSectionSchema;
    editStudentSection?: EditStudentSectionSchema;
    performanceTypes?: PerformanceTypesSchema;
    performanceTypeDetail?: PerformanceTypeDetailSchema;
    addPerformanceType?: AddPerformanceTypeSchema;
    editPerformanceType?: EditPerformanceTypeSchema;
    studentClubs?: StudentClubsSchema;
    studentClubDetail?: StudentClubDetailSchema;
    addStudentClub?: AddStudentClubSchema;
    editStudentClub?: EditStudentClubSchema;
    settingsMainCollege?: SettingsMainCollegeSchema;
    eduModules?: EducationalModulesSchema;
    eduModuleDetail?: EducationalModuleDetailSchema;
    addEduModule?: AddEduModuleSchema;
    editEduModule?: EditEduModuleSchema;
    eduUnitDetail?: EducationalUnitDetailSchema;
    addEduUnit?: AddEduUnitSchema;
    editEduUnit?: EditEduUnitSchema;
    curriculumSubjects?: CurriculumSubjectsSchema;
    curriculumSubjectsDetail?: CurriculumSubjectsDetailSchema;
    addCurriculumSubject?: AddCurriculumSubjectSchema;
    editCurriculumSubject?: EditCurriculumSubjectSchema;
    standardCurriculum?: StandardCurriculumSchema;
    standardCurriculumDetail?: StandardCurriculumDetailSchema;
    addStandardCurriculum?: AddStandardCurriculumSchema;
    editStandardCurriculum?: EditStandardCurriculumSchema;
    educationBases?: EducationBasesSchema;
    workingCurriculum?: WorkingCurriculumSchema;
    workingCurriculumDetail?: WorkingCurriculumDetailSchema;
    addNewWorkingCurriculum?: AddWorkingCurriculumSchema;
    editWorkingCurriculum?: EditWorkingCurriculumSchema;
    workingCurriculumTrainingSchedule?: WorkingCurriculumTrainingScheduleSchema;
    languages?: LanguagesSchema;
    studentGroups?: StudentGroupsSchema;
    studentGroupDetail?: StudentGroupDetailSchema;
    addStudentGroup?: AddStudentGroupSchema;
    editStudentGroup?: EditStudentGroupsSchema;
    trainingSchedule?: TrainingScheduleSchema;
    trainingScheduleDetail?: TrainingScheduleDetailSchema;
    workingCurriculumExtract?: WorkingCurriculumExtractSchema;
    eduActivitiesTypes?: EduActivitiesTypesSchema;
    studentsInGroups?: StudentsInGroupsSchema;
    employees?: EmployeesSchema;
    employeeDetail?: EmployeeDetailSchema;
    addEmployee?: AddEmployeeSchema;
    editEmployee?: EditEmployeeSchema;
    employeesTableFields?: EmployeesTableFieldsSchema;
    employeeCategories?: EmployeeCategoriesSchema;
    employeeCategoryDetail?: EmployeeCategoryDetailSchema;
    addEmployeeCategory?: AddEmployeeCategorySchema;
    editEmployeeCategory?: EditEmployeeCategorySchema;
    employeePositions?: EmployeePositionsSchema;
    employeePositionDetail?: EmployeePositionDetailSchema;
    addEmployeePosition?: AddEmployeePositionSchema;
    editEmployeePosition?: EditEmployeePositionSchema;
    employeeEducations?: EmployeeEducationsSchema;
    employeeEducationDetail?: EmployeeEducationDetailSchema;
    addEmployeeEducation?: AddEmployeeEducationSchema;
    editEmployeeEducation?: EditEmployeeEducationSchema;
    addEmployeeSubject?: AddEmployeeSubjectSchema;
    addEmployeePositionToEmployee?: AddEmployeePositionToEmployeeSchema;
    trainingScheduleSchema?: TrainingScheduleHeaderSchema;
    subjectsSchedule?: SubjectsScheduleSchema;
    subjectsScheduleDetail?: SubjectsScheduleDetailSchema;
    subjectsScheduleDetailActions?: SubjectsScheduleDetailActionsSchema;
    classRooms?: ClassRoomsSchema;
    subjectsScheduleWorkload?: SubjectsScheduleWorkloadSchema;
    addStudentGroupsAssistant?: AddStudentGroupsAssistantSchema;
    autoDistributionStudentGroupsAssistant?: AutoDistributionStudentGroupsSchema;
}

export type StateSchemaKey = keyof StateSchema;

export interface ReducerManager {
    getReducerMap: () => ReducersMapObject<StateSchema>;
    reduce: (state: StateSchema, action: AnyAction) => CombinedState<StateSchema>;
    add: (key: StateSchemaKey, reducer: Reducer) => void;
    remove: (key: StateSchemaKey) => void;
}

export interface ReduxStoreWithManager extends EnhancedStore<StateSchema> {
    reducerManager: ReducerManager;
}

export interface ThunkExtraArg {
    api: AxiosInstance;
    navigate?: (to: To, options?: NavigateOptions) => void;
}

export interface ThunkConfig<T> {
    rejectValue: T;
    extra: ThunkExtraArg;
}
