import { TableFiltersSelectedType } from '../model/types/tableFiltersSelected';

export const tableSelectedFilters: TableFiltersSelectedType = {
    birthDate: {
        from: null,
        to: null,
    },
    student_gender: null,
    student_nationality: null,
    student_citizenship: null,
    student_phone_number: '',
    student_edu_speciality: null,
    student_edu_classifier: null,
    student_study_duration: ['null'],
    student_study_course: ['null'],
    student_edu_form: null,
    arrivalDate: {
        from: null,
        to: null,
    },
    student_enrollment_type: null,
    student_is_arrival_from: null,
    student_is_finished_edu_type: null,
    student_edu_lang: null,
    student_is_has_access_to_exams: false,
    student_residence_type: null,
    student_residential_address: '',
    student_temporary_residence_address: '',
    student_is_need_hostel_type: ['null'],
    student_is_live_at_hostel: false,
    student_financing_source_type: ['null'],
    student_quota: ['null'],
    student_is_orphan: false,
    student_is_without_parental_care: false,
    student_is_disabled_person: false,
    student_material_assistance_type: ['null'],
    student_is_from_young_family: false,
    student_is_study_in_dual_system: false,
    student_is_study_in_productive_employment: false,
    student_is_completed_training_at_competence_center: false,
    student_is_study_in_worldskills: false,
    student_is_involved_in_social_activities: false,
};
