import { StudentsTableFieldsType } from '../model/types/studentsTableFields';

export const studentsTableCheckedFields: StudentsTableFieldsType = {
    student_govid: false,
    student_birth_date: false,
    student_gender: true,
    student_nationality: false,
    student_citizenship: false,
    student_phone_number: false,
    student_edu_speciality: true,
    student_edu_classifier: true,
    student_study_duration: false,
    student_study_course: true,
    student_edu_form: false,
    student_arrival_date: false,
    student_enrollment_type: false,
    student_is_arrival_from: false,
    student_is_finished_edu_type: false,
    student_edu_lang: false,
    student_is_has_access_to_exams: false,
    student_residence_type: false,
    student_residential_address: false,
    student_temporary_residence_add: false,
    student_is_need_hostel_type: false,
    student_is_live_at_hostel: false,
    student_financing_source_type: false,
    student_quota: false,
    student_is_orphan: false,
    student_is_without_parental_care: false,
    student_is_disabled_person: false,
    student_material_assistance_type: false,
    student_is_from_young_family: false,
    student_is_study_in_dual_system: false,
    student_is_study_in_productive_employment: false,
    student_is_completed_training_at_competence_center: false,
    student_is_study_in_worldskills: false,
    student_is_involved_in_social_activities: false,
    id_group: true,
};
